import type { Metadata } from "next";
import { Inter, Rubik } from "next/font/google";
import "./globals.css";
import './globalicons.css'
import Navbar from "@/components/containers/navbar";
import StoreProvider from "@/StoreProvider";
import MobileNav from "@/components/shared/MobileNav";



const inter = Inter({ subsets: ["latin"] });
const rubik = Rubik({
  subsets: ["latin"],
  weight: ['400'],
  variable: '--font-rubik'
})

export const metadata: Metadata = {
  title: "Apple Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className={`${inter.className} ${rubik.variable} bg-[#EEF2F4]`}>
        <StoreProvider>
          <MobileNav />
          <Navbar />
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
