export const buttons = [
  "Behaviour & Personality",
  "Motives & Values",
  "Cognitive Ability",
  "Mental Toughness",
  "360 & Multi-Rater Surveys",
  "Career Development",
  "Innovation & Digitisation",
  "Wellbeing & Engagement",
  "Leadership Development",
  "C-Suite Assessment",
  "Nationalisation Strategy ",
  "High Potential",
  "Recruitment & Selection",
  "Performance Management",
];
